# Generated by Django 2.0.2 on 2018-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
