# Generated by Django 2.0.2 on 2018-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_auto_20180328_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(default='csr', max_length=30),
        ),
    ]
