# Generated by Django 2.0.2 on 2018-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0006_auto_20180328_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
