# Generated by Django 2.0.2 on 2018-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0011_auto_20180408_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
